katipo/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from models import Profile, Run, Url

urlpatterns = patterns('',
    (r'^$', 'django.views.generic.list_detail.object_list', {'queryset':Run.objects.all(), 'template_name':'home.html'}),
    
    url(r'^run/(?P<object_id>\d+)/$', 'katipo.views.run_detail', name="katipo-run-detail"),
    url(r'^run/(?P<run_id>\d+)/url/$', 'katipo.views.url_detail', name="katipo-url-detail"),
    
    (r'^url/$', 'katipo.views.url_search'),
    
    (r'^profile/$', 'django.views.generic.list_detail.object_list', {'queryset':Profile.objects.all()}),
    url(r'^profile/(?P<object_id>\d+)/$', 'django.views.generic.create_update.update_object', {'model':Profile}, name="katipo-profile-detail"),
    (r'^profile/new/$', 'django.views.generic.create_update.create_object', {'model':Profile}),
    
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

katipo/models.py
import urlparse
import datetime
import urllib

from django.db import models
from django.core.urlresolvers import reverse

from utils.fields import PythonField, TimedeltaField

class Profile(models.Model):
    name = models.CharField(max_length=200, unique=True)
    settings = PythonField(blank=True)
    
    def __unicode__(self):
        return unicode(self.name)
    
    @models.permalink
    def get_absolute_url(self):
        return ('katipo-profile-detail', [str(self.id)])
    
    @property
    def start_urls(self):
        return self.get_settings_module().get('START_URLS', ())
    
    @property
    def ignore_url_match(self):
        return self.get_settings_module().get('IGNORE_URL_MATCH', ())
    
    @property
    def extra_hosts(self):
        return self.get_settings_module().get('EXTRA_HOSTS', ())
    
    @property
    def test_externals(self):
        return self.get_settings_module().get('TEST_EXTERNALS', True)
    
    @property
    def parse_content_types(self):
        return self.get_settings_module().get('PARSE_CONTENT_TYPES', (r'^text/', r'^application/xhtml+xml$'))
    
    @property
    def expected_errors(self):
        return self.get_settings_module().get('EXPECTED_ERRORS', ())
    
    def get_run_latest(self):
        try:
            return self.runs.all()[0]
        except IndexError, e:
            return None
    
    def get_run_previous(self):
        try:
            return self.runs.all()[1]
        except IndexError, e:
            return None

class Run(models.Model):
    STATUS_RUNNING = 'RUNNING'
    STATUS_COMPLETE = 'COMPLETE'
    STATUS_ABORTED = 'ABORTED'
    
    CHOICES_STATUS = (
        (STATUS_RUNNING, 'Running'),
        (STATUS_COMPLETE, 'Complete'),
        (STATUS_ABORTED, 'Aborted'),
    )
    
    name = models.CharField(max_length=200, blank=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=STATUS_RUNNING)
    started_at = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile, related_name='runs')
    elapsed_time = TimedeltaField(null=True)
    
    class Meta:
        ordering = ('-started_at',)
    
    def __unicode__(self):
        return unicode(self.name) or u"%s @ %s (#%d)" % (self.profile, self.started_at, self.id)
    
    @models.permalink
    def get_absolute_url(self):
        return ('katipo-run-detail', [str(self.id)])
    
    @property
    def count_crawled(self):
        return self.urls.exclude(result='').count()
    @property
    def count_ignored(self):
        return self.urls.filter(result=Url.RESULT_IGNORED).count()
    @property
    def count_not_crawled(self):
        return self.urls.filter(result='').count()
    @property
    def count_internal(self):
        return self.urls.filter(is_internal=True).exclude(result='').count()
    @property
    def count_external(self):
        return self.urls.filter(is_internal=False).exclude(result='').count()
    @property
    def count_good(self):
        return self.urls.filter(result=Url.RESULT_GOOD).count()
    @property
    def count_bad(self):
        return self.urls.filter(result=Url.RESULT_BAD).count()
    @property
    def count_errors(self):
        return self.urls.filter(result=Url.RESULT_ERROR).count()
    @property
    def count_timeouts(self):
        return self.urls.filter(result=Url.RESULT_TIMEOUT).count()
    
    def _percent(self, quantity):
        # handle div/zero
        return 100.0 * quantity / self.count_crawled if self.count_crawled else 0.0
    
    @property
    def count_internal_pc(self):
        return self._percent(self.count_internal)
    @property
    def count_external_pc(self):
        return self._percent(self.count_external)
    @property
    def count_good_pc(self):
        return self._percent(self.count_good)
    @property
    def count_bad_pc(self):
        return self._percent(self.count_bad)
    @property
    def count_errors_pc(self):
        return self._percent(self.count_errors)
    @property
    def count_timeouts_pc(self):
        return self._percent(self.count_timeouts)
    
    def get_good(self):
        return self.urls.filter(result=Url.RESULT_GOOD)
    def get_bad(self):
        return self.urls.filter(result=Url.RESULT_BAD)
    def get_errors(self):
        return self.urls.filter(result=Url.RESULT_ERROR)
    def get_timeouts(self):
        return self.urls.filter(result=Url.RESULT_TIMEOUT)
    def get_ignored(self):
        return self.urls.filter(result=Url.RESULT_IGNORED)
    def get_not_crawled(self):
        return self.urls.filter(result='')
    def get_all_errors(self):
        return self.urls.exclude(result__in=(Url.RESULT_GOOD, Url.RESULT_IGNORED, '')).order_by('result', 'status_code', 'url')

class UrlManager(models.Manager):
    def distinct_urls(self):
        from django.db import connection
        cursor = connection.cursor()
        cursor.execute("SELECT DISTINCT url FROM katipo_url ORDER BY url")
        return tuple([row[0] for row in cursor.fetchall()])
        
    def search(self, url_string):
        """ 
        Return newest instances of each URL found by a search:
            1. Exact matches (if include_exact)
            2. Starts-with (case sensitive)
            3. Starts-with (case-insensitive)
            4. Contains (case-sensitive)
            5. Contains (case-insensitive)
        
        Result is formatted as a dictionary:
        {
            'exact' : <exact-match Url or None>,
            'inexact': [<ordered list of inexact matches>],
        }
        """
        #FIXME: Make it actually do the above
        
        exact = Url.objects.filter(url=url_string)[:1]
        url_exact = len(exact) and exact[0] or None 
        
        r = {
            'exact': url_exact,
            'inexact': (),
        }
        return r
        

class Url(models.Model):
    RESULT_GOOD = 'GOOD'
    RESULT_BAD = 'BAD'
    RESULT_ERROR = 'ERROR'
    RESULT_TIMEOUT = 'TIMEOUT'
    RESULT_IGNORED = 'IGNORED'
    
    CHOICES_RESULT = (
        (RESULT_GOOD, 'Good (expected status)'),
        (RESULT_BAD, 'Bad (unexpected status)'),
        (RESULT_ERROR, 'Error'),
        (RESULT_TIMEOUT, 'Timeout'),
        (RESULT_IGNORED, 'Ignored'),
    )
    
    objects = UrlManager()
    
    run = models.ForeignKey(Run, related_name='urls')
    url = models.CharField(max_length=4096, db_index=True)
    
    result = models.CharField(max_length=10, blank=True, choices=CHOICES_RESULT, db_index=True)
    status_code = models.IntegerField(null=True, db_index=True)
    elapsed_time = TimedeltaField(null=True, db_index=True)
    is_internal = models.BooleanField(default=False, db_index=True)
    
    outgoing_links = models.ManyToManyField('self', symmetrical=False, related_name='incoming_links', blank=True)
    
    class Meta:
        unique_together = (('run', 'url'),)
        ordering = ('url', 'run',)
    
    def __unicode__(self):
        return u"%s - %s" % (self.url, self.result or 'NOT_CRAWLED')
    
    def get_absolute_url(self):
        u = reverse('katipo-url-detail', args=(self.run_id,))
        u += "?" 
        u += urllib.urlencode({'u':self.url})
        return u
    
    def get_domain(self, include_scheme=True):
        up = self.url_parts
        if include_scheme:
            return urlparse.urlunsplit((up.scheme, up.netloc, None, None, None))
        else:
            return up.netloc
    
    def get_all_runs(self):
        return Url.objects.filter(url=self.url)
    
    @property
    def url_parts(self):
        return urlparse.urlsplit(self.url)

    

katipo/templates/katipo/_url_table.html
<table class="url_list">
    <thead>
        <th>URL</th>
        <th>Response Code</th>
        <th>Response Time</th>
    </thead>
    <tbody>
        {% for url in urls %}
        <tr class="url_{{url.result}}">
            <th><a href="{{ url.get_absolute_url }}">{{ url.url }}</a></th>
            <td>{{ url.status_code }}</td>
            <td>{{ url.elapsed_time }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

katipo/templates/katipo/profile_form.html
{% extends "base.html" %}

{% block title %}Profiles - New{% endblock title %}

{% block content_sidebar %}
<ul>
    <li><a href="/profile/">Manage Profiles</a></li>
</ul>
{% endblock %}

{% block content_main %}
    <h1>Edit Profile</h1>
    
    <form action="" method="POST">
        {{ form.as_p }}
        
        <button type="submit">Save</button>
    </form>
{% endblock content_main %}

katipo/templates/katipo/profile_list.html
{% extends "base.html" %}

{% block title %}Profiles{% endblock title %}

{% block content_main %}
    <h1>Profiles</h1>
    
    <table>
        <tbody>
            {% for o in object_list %}
            <tr>
                <th><a href="{{o.get_absolute_url}}">{{o}}</a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content_main %}

{% block content_sidebar %}
    <a href="new/">Create new Profile</a>
{% endblock content_sidebar %}

katipo/templates/katipo/run_detail.html
{% extends "base.html" %}
{% load katipo_run %}

{% block title %}Run {{run}}{% endblock %}

{% block head %}
    {{ block.super }}
    <script type="text/javascript">
        dojo.require("dijit.layout.TabContainer");
        dojo.require("dijit.layout.ContentPane");
    </script>
{% endblock head %}

{% block content_sidebar %}
<form action="" method="GET">
    {{ compare_list_form.as_p }}
    <p><button type="submit">Update</button></p>
</form>
{% endblock content_sidebar %}

{% block content_main %}
<h1>Run {{run}}</h1>

<table class="detail">
    <thead>
        <tr>
            <th>Item</th>
            <th>Value</th>
            {% if compare_run %}<th>Change</th>{% endif %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Profile</th>
            <td><a href="{{run.profile.get_absolute_url}}">{{ run.profile }}</a></td>
        </tr>
        <tr>
            <th>Started at</th>
            <td>{{ run.started_at }}</td>
        </tr>
        <tr>
            <th>Elapsed Time</th>
            <td>{{ run.elapsed_time }}</td>
            {% if compare_run %}<td><span title="{{compare_run.elapsed_time}}">{% percent_change run.get_elapsed_time_seconds compare_run.get_elapsed_time_seconds %}</span></td>{% endif %}
        </tr>
        <tr>
            <th>Crawled URLs</th>
            <td>{{ run.count_crawled }}</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_crawled}}">
                    {% percent_change run.count_crawled compare_run.count_crawled %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Ignored</th>
            <td>{{ run.count_ignored }}</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_ignored}}">
                    {% percent_change run.count_ignored compare_run.count_ignored %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Not crawled</th>
            <td>{{ run.count_not_crawled }}</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_not_crawled}}">
                    {% percent_change run.count_not_crawled compare_run.count_not_crawled %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Internal URLs</th>
            <td>{{ run.count_internal }}</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_internal}}">
                    {% percent_change run.count_internal compare_run.count_internal %}
                </span>
            </td>
            {% endif %}
            <td rowspan="2">
                <img src="http://chart.apis.google.com/chart?cht=p3&amp;chs=300x100&amp;chd=t:{{run.count_internal_pc|floatformat:1}},{{run.count_external_pc|floatformat:1}}&amp;chl=Internal|External" />
            </td>
        </tr>
        <tr>
            <th>External URLs</th>
            <td>{{ run.count_external }}</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_external}}">
                    {% percent_change run.count_external compare_run.count_external %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Good URLs</th>
            <td>{{ run.count_good }} ({{ run.count_good_pc|floatformat:1 }}%)</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_good}} ({{ compare_run.count_good_pc|floatformat:1 }}%)">
                    {% percent_change run.count_good compare_run.count_good %}
                </span>
            </td>
            {% endif %}
            <td rowspan="4">
                <img src="http://chart.apis.google.com/chart?cht=p3&amp;chs=300x100&amp;chd=t:{{run.count_good_pc|floatformat:1}},{{run.count_bad_pc|floatformat:1}},{{run.count_errors_pc|floatformat:1}},{{run.count_timeouts_pc|floatformat:1}}&amp;chl=Good|Bad|Errors|Timeouts&amp;chco=00FF00,FF0000,FF8C00,FFD700" />
            </td>
        </tr>
        <tr>
            <th>Bad URLs</th>
            <td>{{ run.count_bad }} ({{ run.count_bad_pc|floatformat:1 }}%)</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_bad}} ({{ compare_run.count_bad_pc|floatformat:1 }}%)">
                    {% percent_change run.count_bad compare_run.count_bad %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Error URLs</th>
            <td>{{ run.count_errors }} ({{ run.count_errors_pc|floatformat:1 }}%)</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_errors}} ({{ compare_run.count_errors_pc|floatformat:1 }}%)">
                    {% percent_change run.count_errors compare_run.count_errors %}
                </span>
            </td>
            {% endif %}
        </tr>
        <tr>
            <th>Timeout URLs</th>
            <td>{{ run.count_timeouts }} ({{ run.count_timeouts_pc|floatformat:1 }}%)</td>
            {% if compare_run %}
            <td>
                <span title="{{compare_run.count_timeouts}} ({{ compare_run.count_timeouts_pc|floatformat:1 }}%)">
                    {% percent_change run.count_timeouts compare_run.count_timeouts %}
                </span>
            </td>
            {% endif %} 
        </tr>
    </tbody>
</table>

<div dojoType="dijit.layout.TabContainer" id="url_tabs" tabStrip="true">
    <div dojoType="dijit.layout.ContentPane" title="Bad URLs ({{run.count_bad}})" href="?result=BAD"></div>
    <div dojoType="dijit.layout.ContentPane" title="Error URLs ({{run.count_errors}})" href="?result=ERROR"></div>
    <div dojoType="dijit.layout.ContentPane" title="Timeout URLs ({{run.count_timeouts}})" href="?result=TIMEOUT"></div>
    <div dojoType="dijit.layout.ContentPane" title="Good URLs ({{run.count_good}})" href="?result=GOOD"></div>
    <div dojoType="dijit.layout.ContentPane" title="Ignored ({{run.count_ignored}})" href="?result=IGNORED"></div>
    <div dojoType="dijit.layout.ContentPane" title="Not crawled ({{run.count_not_crawled}})" href="?result="></div>
</div>
{% endblock content_main %}

katipo/templates/katipo/url_detail.html
{% extends "base.html" %}

{% block title %}URL {{url}}, Run {{ url.run }}{% endblock %}

{% block head %}
    {{ block.super }}
    <script type="text/javascript">
        dojo.require("dijit.layout.TabContainer");
        dojo.require("dijit.layout.ContentPane");
    </script>
{% endblock %}

{% block content_sidebar %}
Current Run:
<form action="" method="GET">
    {{ run_form.as_p }}
    <p><button type="submit">Update</button></p>
</form>
{% endblock content_sidebar %}

{% block content_main %}
<h1><a href="{{url.url}}">{{ url.url }}</a></h1>
<h2>Run <a href="{{url.run.get_absolute_url}}">{{url.run}}</a></h2>

<table class="detail">
    <tbody>
        <tr>
            <th>Result</th>
            <td>{{ url.get_result_display|default:"Not Crawled" }}</td>
        </tr>
        <tr>
            <th>Response code</th>
            {% if url.result %}
                <td>{{ url.status_code }}</td>
            {% else %}
                <td>Not crawled</td>
            {% endif %}
        </tr>
        <tr>
            <th>Elapsed Time</th>
            {% if url.result %}
                <td>{{ url.elapsed_time }}</td>
            {% else %}
                <td>Not crawled</td>
            {% endif %}
        </tr>
        <tr>
            <th>Incoming Links</th>
            <td>{{ url.incoming_links.count }}</td>
        </tr>
        <tr>
            <th>Outgoing Links</th>
            {% if url.result %}
                <td>{{ url.outgoing_links.count }}</td>
            {% else %}
                <td>Not crawled</td>
            {% endif %}
        </tr>
    </tbody>
</table>

<div dojoType="dijit.layout.TabContainer" id="url_tabs" tabStrip="true" class="url_colors">
    <div dojoType="dijit.layout.ContentPane" title="Incoming Links ({{url.incoming_links.all.count}})" href="?u={{url.url|urlencode}}&amp;links=incoming"></div>
    <div dojoType="dijit.layout.ContentPane" title="Outgoing Links ({{url.outgoing_links.all.count}})" href="?u={{url.url|urlencode}}&amp;links=outgoing"></div>
</div>

{% endblock content_main %}

katipo/templates/katipo/url_search.html
{% extends "base.html" %}

{% block title %}URL Search{% endblock %}

{% block content_main %}
<h1>URL Search</h1>

<form action="" method="GET">
    <label>Go to URL: <input type="text" name="url"></label>
    <button type="submit">Go</button>
</form>

{% if search %}
    <h2>Results for <code>{{search}}</code>:</h2>
    
    {% if notfound %}
        <p class="error">Sorry, we couldn't find any matching URLs</p>
    {% else %}
        <h3>Exact Match</h3>
        <ul>
            {% if urls.exact %}
            <li><a href="{{urls.exact.get_absolute_url}}">{{urls.exact.url}}</a> (in {{urls.exact.get_all_runs.count}} runs)</li>
            {% else %}
            <li class="warn">No exact match found.</li>
            {% endif %}
        </ul>
    
        <h3>Inexact Matches</h3>
        <ul>
        {% if urls.inexact %}
            {% for url in urls.inexact %}
                <li><a href="{{url.get_absolute_url}}">{{url}}</a></li>
            {% endfor %}
        {% else %}
            <li class="warn">No inexact matches found.</li>
        {% endif %}
        </ul>
    {% endif %}
{% endif %}
{% endblock content_main %}